### ISSUE TITLE
type should be tif 

### ISSUE THREAD

**Issue by vincentsarago** [Terradue/stac-resources#1]
👋 sorry to drop by but just noticed the media type doesn't match with the files extension 
I should maybe be: `"image/tiff; application=geotiff; profile=cloud-optimized"`

https://github.com/Terradue/stac-resources/blob/1aebd3e6b0069adf4515123d248137c0ea59d6f5/kompsat-3a/item.json#L116-L117

**Comment by fabricebrito** [comment]
Hello @vincentsarago. Yes, the media type was wrong. Thanks for spotting this!
Feel free to drop by. We'll be adding more resources for several other EO missions.
